Import Fvwm 2.2.5. See the ANNOUNCE file for more info on the changes

diff --git a/xc/programs/fvwm/utils/fvwmrc_convert b/xc/programs/fvwm/utils/fvwmrc_convert
--- a/xc/programs/fvwm/utils/fvwmrc_convert
+++ b/xc/programs/fvwm/utils/fvwmrc_convert
@@ -17,40 +17,78 @@
 # case of the fvwm commands must match those in the script
 # exactly). With gawk, it'll be case-insensitive.
 
+# It's not perfect: some old commands slip through, especially in the
+# context of Mouse and Key commands.  But it provides a good basis on
+# which to go further.
+
 #
-# Convert fvwm 1.x configuration file to 2.0
+# Convert fvwm 1.x configuration file to 2.2 configuration file
 #
 # Originally written by Martin Kraemer <Martin.Kraemer@mch.sni.de>
 # Corrected, extended, and modified by Grant McDorman <grant@isgtec.com>
 # 24 May 95
-# Addtional corrections and extensions by Bill Oswald <wamo@vnet.ibm.com>
+# Additional corrections and extensions by Bill Oswald <wamo@vnet.ibm.com>
 # 8 Mar 96 thru 18 Jul 96
 # Minor corrections to make it easier to customize by Charles Hines 08/01/96
-#
+# Further minor corrections by Julian Gilbey <jdg@debian.org> based on those
+# of Austin Donnelly <and1000@debian.org>, 1 Mar 1999
+# Further major corrections by Julian Gilbey <jdg@debian.org>, 3 Mar 1999
+# and minor corrections March - May 1999.
+# Correct some major gaffs: Julian Gilbey, January 2000, with thanks to
+# Victor Meghesan <victorm@genesys.ro>
 
-echo "fvwmrc-to-fvwm2rc"
+echo "fvwmrc-to-fvwm2rc" >&2
 
-# Point this to your gawk/nawk/awk exec:
-AWK=/usr/local/bin/gawk
-#AWK=/bin/awk
+# gawk has IGNORECASE, so we use it if possible.
+if [ -n `command -v gawk 2>/dev/null` ]
+then
+   AWK=`command -v gawk`
+elif [ -x /usr/bin/gawk ]
+then
+   AWK=/usr/bin/gawk
+elif [ -n `command -v awk 2>/dev/null` ]
+then
+   AWK=`command -v awk`
+elif [ -x /usr/bin/awk ]
+then
+   AWK=/usr/bin/awk
+fi
 
 if [ ! -x $AWK ];then
-   echo "$AWK missing, cannot run"
+   echo "Can't find any awk, cannot run!" >&2
    exit 1
 fi
+
 source=${1:-$HOME/.fvwmrc}
+if [ ! -r $source ] ; then
+	echo "Can't find source file $source, giving up" >&2
+	exit 1
+fi
+
 dest=${2:-$HOME/.fvwm2rc}
 if [ "$dest" != "-" ] ;then
-	echo "Output to $dest"
+	echo "Output to $dest" >&2
 	if [ -f $dest ] ; then
-	  mv $dest $dest.bak
-	  echo "Saving existing $dest as $dest.bak"
+	  echo "Saving existing $dest as $dest.bak" >&2
+	  cp -p $dest $dest.bak || { echo "Couldn't save; aborting" >&2; exit 1; }
+	else
+	  cp -p $source $dest 2>/dev/null  # try to preserve permissions
 	fi
-	exec >$dest
+	exec >$dest || { echo "Couldn't write to $dest, aborting" >&2; exit 1; }
+	TTY=`tty`
+	if [ ! -w "$TTY" ] ;then
+	  TTY=/dev/stderr
+	fi
+else
+	TTY=/dev/stderr
 fi
+if [ ! -w "$TTY" ] ;then
+	TTY=/dev/null
+fi
+
 cat $source | $AWK '
 BEGIN   {
-        printf ("# Trying to compile an old .fvwrc to the  new fvwm-2.0 Format\n");
+        printf ("# Trying to compile an old .fvwrc to the new fvwm-2.xx Format\n");
 	TRUE=1; FALSE=0;
 
 	IGNORECASE=TRUE;
@@ -61,13 +99,6 @@ BEGIN   {
 
 	stdforecolor="";            dflt["stdforecolor"] = "black";
 	stdbackcolor="";            dflt["stdbackcolor"] = "grey70";
-
-	menuforecolor="";           dflt["menuforecolor"] = "black";
-	menubackcolor="";           dflt["menubackcolor"] = "grey70";
-	menustipplecolor="";        dflt["menustipplecolor"] = "grey40";
-	font="";                    dflt["font"] = "-adobe-helvetica-medium-r-*-*-18-*-*-*-*-*-iso8859-1";
-	mwmmenus="";                dflt["mwmmenus"] = "fvwm";
-	menustyle=FALSE;
 
 	inpopup=FALSE;
 	infunction=FALSE;
@@ -81,14 +112,19 @@ BEGIN   {
 	next;
 }
 
-/^$/                            {   # Empty line, pass it thru
+/^[ \t]*$/                            {   # Empty line, pass it thru
 	print $0;
 	next;
 }
 	
 ################ Rename common items ##############
-/Restart/ && /fvwm/             { gsub("fvwm", "fvwm2"); } # try and leave paths alone
+/Restart/ && /fvwm/             {
+	gsub("fvwm", "fvwm2"); gsub("fvwm22","fvwm2"); # try to leave paths alone
+}
 /GoodStuff/                     { gsub("GoodStuff", "FvwmButtons"); }
+
+############ Chop off trailing "&" from Exec commands ##########
+/^Exec[ \t]+/ || /[ \t]+Exec[ \t]+/ { gsub ("\&[ \t]*$",""); }
 
 ################ Highlight Colors ##############
 /^[ \t]*HiBackColor[ \t]*/	{
@@ -118,62 +154,32 @@ BEGIN   {
 
 ########## Menu Colors, Style and Font ###########
 /^[ \t]*MenuForeColor[ \t]*/	{
-        dflt["menuforecolor"]=menuforecolor=$2;
-	printf ("#!%s (new command=MenuStyle)\n", $0);
-	if (menubackcolor != "" && menuforecolor != "" && menustipplecolor != "" && font != "" && mwmmenus != "" && !menustyle) {
-           printf ("\n#Set the foreground, background and stipple color and font for menus\n");
-	   printf ("MenuStyle   %s %s %s %s %s\n", menuforecolor, menubackcolor, menustipplecolor, font, mwmmenus);
-	   menustyle=TRUE;
-	} else
-	   menustyle=FALSE;
-        next;
+	printf ("#!%s\n", $0);
+	printf ("MenuStyle * Foreground %s\n", $2);
+	next;
 }
 
 /^[ \t]*MenuBackColor[ \t]*/	{
-        dflt["menubackcolor"]=menubackcolor=$2;
-	printf ("#!%s (new command=MenuStyle)\n", $0);
-	if (menubackcolor != "" && menuforecolor != "" && menustipplecolor != "" && font != "" && mwmmenus != "" && !menustyle) {
-           printf ("\n#Set the foreground, background and stipple color and font for menus\n");
-	   printf ("MenuStyle   %s %s %s %s %s\n", menuforecolor, menubackcolor, menustipplecolor, font, mwmmenus);
-	   menustyle=TRUE;
-        } else
-	   menustyle=FALSE;
-        next;
+	printf ("#!%s\n", $0);
+	printf ("MenuStyle * Background %s\n", $2);
+	next;
 }
 
 /^[ \t]*MenuStippleColor[ \t]*/	{
-        dflt["menustipplecolor"]=menustipplecolor=$2;
-	printf ("#!%s (new command=MenuStyle)\n", $0);
-	if (menubackcolor != "" && menuforecolor != "" && menustipplecolor != "" && font != "" && mwmmenus != "" && !menustyle) {
-           printf ("\n#Set the foreground, background and stipple color and font for menus\n");
-	   printf ("MenuStyle   %s %s %s %s %s\n", menuforecolor, menubackcolor, menustipplecolor, font, mwmmenus);
-	   menustyle=TRUE;
-        } else
-	   menustyle=FALSE;
-        next;
+	printf ("#!%s\n", $0);
+	printf ("MenuStyle * Greyed %s\n", $2);
+	next;
 }
 
 /^[ \t]*MWMMenus[ \t]*/		{
-        dflt["mwmmenus"]=mwmmenus="mwm";
-	printf ("#!%s (new command=MenuStyle)\n", $0);
-	if (menubackcolor != "" && menuforecolor != "" && menustipplecolor != "" && font != "" && mwmmenus != "" && !menustyle) {
-           printf ("\n#Set the foreground, background and stipple color and font for menus\n");
-	   printf ("MenuStyle   %s %s %s %s %s\n", menuforecolor, menubackcolor, menustipplecolor, font, mwmmenus);
-	   menustyle=TRUE;
-	} else
-	   menustyle=FALSE;
+	printf ("#!%s\n", $0);
+	printf ("MenuStyle * mwm\n");
 	next;
 }
 
 /^[ \t]*Font[ \t]*/		{
-        dflt["font"]=font=$2;
-	printf ("#!%s (new command=MenuStyle)\n", $0);
-	if (menubackcolor != "" && menuforecolor != "" && menustipplecolor != "" && font != "" && mwmmenus != "" && !menustyle) {
-           printf ("\n#Set the foreground, background and stipple color and font for menus\n");
-	   printf ("MenuStyle   %s %s %s %s %s\n", menuforecolor, menubackcolor, menustipplecolor, font, mwmmenus);
-	   menustyle=TRUE;
-	} else
-	   menustyle=FALSE;
+	printf ("#!%s\n", $0);
+	printf ("MenuStyle * Font %s\n", $2);
 	next;
 }
 
@@ -182,20 +188,20 @@ BEGIN   {
 /^[ \t]*ButtonStyle[ \t]*/	{
         if ($2 == ":") {  # new style already
            if (NF != $4+4)
-	       print "ERROR: ButtonStyle command incorrect" >"/dev/stderr";
+	       print "ERROR: ButtonStyle command incorrect\n" NR ": " $0 >"'$TTY'";
 	   printf ("%s %d %d", $1, $3, $4);
 	   for (i=5; i<=NF; ++i)
 	       printf (" %s", $i);
 	   printf ("\n");
 	} else {
            print "Note: Conversion of old ButtonStyle; values rounded" \
-			>"/dev/stderr"
+			>"'$TTY'"
 	   printf ("#!         Old line was: %s\n", $0);
 	   p=index ($3,"x");
 	   x=substr($3,1,p-1)/2;
 	   y=substr($3,p+1)/2;
 	   printf ("%s %s 5 %dx%d@0 %dx%d@0 %dx%d@0 %dx%d@1 %dx%d@1\n",
-		    $1, $2, 50-x,50+y, 50+x,50+y, 50-x,50-y, 50+x,50-y,
+		    $1, $2, 50-x,50+y, 50+x,50+y, 50+x,50-y, 50-x,50-y,
 		    50-x,50+y);
 	}
 	next;
@@ -221,9 +227,9 @@ BEGIN   {
 /^[ \t]*IconFont[ \t]*/		{ print $0; next; }
 /^[ \t]*SuppressIcons[ \t]*/	{ print "Style \"*\" NoIcon"; next; }
 /^[ \t]*StickyIcons[ \t]*/	{ print "Style \"*\" StickyIcon"; next; }
-/^[ \t]*ModulePath[ \t]*/	{ gsub("/fvwm", "/fvwm2"); print $0; next; }
-/^[ \t]*PixmapPath[ \t]*/	{ gsub("/fvwm", "/fvwm2"); print $0; next; }
-/^[ \t]*IconPath[ \t]*/		{ gsub("/fvwm", "/fvwm2"); print $0; next; }
+/^[ \t]*ModulePath[ \t]*/	{ print "#! (ModulePath command commented out)\n#" $0; next; }
+/^[ \t]*PixmapPath[ \t]*/	{ print $0; next; }
+/^[ \t]*IconPath[ \t]*/		{ print $0; next; }
 # note: Icon must be followed by some white space
 /^[ \t]*Icon[ \t]+/		{ printf "Style %s Icon %s\n", $2, $3; next; }
 
@@ -238,7 +244,10 @@ BEGIN   {
 ########## Placement & Focus styles ##########
 /^[ \t]*RandomPlacement[ \t]*/	{ print "Style \"*\" " $0; placement = TRUE; next; }
 /^[ \t]*SmartPlacement[ \t]*/	{ print "Style \"*\" " $0; placement = TRUE; next; }
-/^[ \t]*Sticky[ \t]*/		{ printf "Style \"%s\" Sticky\n", $2; next; }
+/^[ \t]*Sticky(Back|Fore)Color[ \t]*/ {
+      print "#! " $0 " (not supported in FVWM2)"; next;
+}
+/^[ \t]*Sticky[ \t]+/		{ printf "Style \"%s\" Sticky\n", $2; next; }
 /^[ \t]*NoPPosition[ \t]*/	{ print "Style \"*\" " $0; next; }
 /^[ \t]*ClickToFocus[ \t]*/	{ print "Style \"*\" " $0; next; }
 /^[ \t]*SloppyFocus[ \t]*/	{ print "Style \"*\" " $0; next; }
@@ -265,28 +274,63 @@ BEGIN   {
 ########## Etc ##########
 /^[ \t]*Lenience[ \t]*/		{ print "Style \"*\" " $0; next; }
 /^[ \t]*Style[ \t]*/		{ print $0; next; }
+# Key keyname context mods (Exec|Module|Restart) ...
+#  used to be followed by a "name"; it is no longer
+/^[ \t]*Key[ \t]+[^ \t]+[ \t]+[^ \t]+[ \t]+[^ \t]+[ \t]+(Exec|Module|Restart)[ \t]+\"/  {
+	# not going to handle escaped quotes
+	label=$6;
+	first=7;
+	quoted=substr(label, 1, 1)=="\"" &&
+		substr(label, length(label), 1)!="\"";
+	for (i=7;i<=NF && quoted;i++) {
+		label=$i;
+		quoted=substr(label, length(label), 1)!="\"";
+		first=i + 1;
+	}
+	printf ("%s %s %s %s %s", $1, $2, $3, $4, $5);
+	for (i=first; i<=NF; ++i)
+		printf (" %s", $i);
+	printf ("\n");
+	next;
+}
+# Any other Key command
 /^[ \t]*Key[ \t]*/		{ print $0; next; }
-/^[ \t]*Mouse[ \t]*/		{
-	if (sub("[ 	]Pop[uU]p[ 	]", " Menu ")) {
-	    if (!warn["Mouse"]) {
-		print "Note: Setting mouse bindings to sticky menus">"/dev/stderr";
-		warn["Mouse"] = TRUE;
-	    }
-	    if (index($6, "\"") == 1) {
-	       gsub("\"", "")
-	       if (NF > 6) {
-	          for (i = 6; i <= NF; i++)
-                    sub($i " ", $i)
-	       }
-	    } 
-	    sub("$", " Nop");
- 	}
-	print $0; next;
+
+# Similarly with Mouse commands
+/^[ \t]*Mouse[ \t]+[^ \t]+[ \t]+[^ \t]+[ \t]+[^ \t]+[ \t]+(Exec|Module|Restart)[ \t]+\"/  {
+	# not going to handle escaped quotes
+	label=$6;
+	first=7;
+	quoted=substr(label, 1, 1)=="\"" &&
+		substr(label, length(label), 1)!="\"";
+	for (i=7;i<=NF && quoted;i++) {
+		label=$i;
+		quoted=substr(label, length(label), 1)!="\"";
+		first=i + 1;
+	}
+	printf ("%s %s %s %s %s", $1, $2, $3, $4, $5);
+	for (i=first; i<=NF; ++i)
+		printf (" %s", $i);
+	printf ("\n");
+	next;
 }
 
-/^[ \t]*WindowListSkip[ \t]*/	{ printf "Style %s WindowListSkip", $2; next; }
+/^[ \t]*Mouse[ \t]*/		{ print $0; next; }
+# This is probably not necessary
+# /^[ \t]*Mouse[ \t]*/		{
+# 		 if (sub("[ \t]Pop[uU]p[ \t]", " Menu ")) {
+# 			  if (!warn["Mouse"]) {
+# 			 print "Note: Setting mouse bindings to sticky menus">"'$TTY'";
+# 			 warn["Mouse"] = TRUE;
+# 			  }
+# 			  sub("$", " Nop");
+# 		 }
+# 		 print $0; next;
+# }
+
+/^[ \t]*WindowListSkip[ \t]*/	{ printf "Style %s WindowListSkip\n", $2; next; }
 /^[ \t]*WindowFont[ \t]*/	{ print $0; next; }
-/^[ \t]*ClickTime[ \t]*/		{ print $0; next; }
+/^[ \t]*ClickTime[ \t]*/	{ print $0; next; }
 /^[ \t]*OpaqueMove[ \t]*/	{ print "OpaqueMoveSize " $2; next; }
 /^[ \t]*EdgeScroll[ \t]*/	{ print $0; next; }
 /^[ \t]*EdgeResistance[ \t]*/	{ print $0; next; }
@@ -297,17 +341,18 @@ BEGIN   {
 	next;
 }
 
-/^[ \t]**FvwmButtons[ \t]*/	{
+/^[ \t]*FvwmButtons[ \t]*/	{
 	sub("[ 	]Swallow[ 	]*[^ 	]*", "& Exec");
 	print $0;
 	if (length($0) > 199)
 	{
-	    print "Warning: line too long" >"/dev/stderr";
-	    print ">> " $0 >"/dev/stderr";
+	    print "Warning: line" NR "too long" >"'$TTY'";
+	    print ">> " $0 >"'$TTY'";
 	}
 	if (!warn["GoodStuff"])
 	{
-	    print "Note: GoodStuff renamed to FvwmButtons" >"/dev/stderr";
+	    print "Note: GoodStuff renamed to FvwmButtons" >"'$TTY'";
+	    print "Note: FvwmButtons syntax may now be wrong; please check!" >"'$TTY'";
 	    warn["GoodStuff"]=TRUE;
 	}
 	next;
@@ -326,10 +371,10 @@ BEGIN   {
 # hack: function declarations cannot have leading whitespace
 /^Function[ \t]*/		{
 	if (inpopup)
-	   print "ERROR: EndPopup missing\n" NR $0 >"/dev/stderr";
+	   print "ERROR: EndPopup missing\n" NR ": " $0 >"'$TTY'";
 	inpopup=FALSE;
 	if (infunction)
-	   print "ERROR: EndFunction missing\n" NR $0 >"/dev/stderr";
+	   print "ERROR: EndFunction missing\n" NR ": " $0 >"'$TTY'";
 	infunction=TRUE;
 	prefix="AddToFunc " $2;
 	next;
@@ -337,7 +382,7 @@ BEGIN   {
 
 /^[ \t]*EndFunction[ \t]*/	{
         if (!infunction)
-           print "ERROR: EndFunction outside of function" >"/dev/stderr";
+           print "ERROR: EndFunction outside of function" >"'$TTY'";
 	infunction=FALSE;
 	prefix="";
 	next;
@@ -346,25 +391,32 @@ BEGIN   {
 # hack: popup declarations cannot have leading whitespace
 /^Popup/                        {
         if (inpopup) 
-	   print "ERROR: EndPopup missing\n" NR $0 >"/dev/stderr";
+	   print "ERROR: EndPopup missing\n" NR ": " $0 >"'$TTY'";
         if (infunction)
-	   print "ERROR: EndFunction missing\n" NR $0 >"/dev/stderr";
+	   print "ERROR: EndFunction missing\n" NR ": " $0 >"'$TTY'";
         infunction=FALSE;
 	inpopup=TRUE;
 
+	label=$2;
 	if (index($2, "\"") == 1) {
-	   tstr = ""
-	   for (i = 2; index(substr($i, 2), "\"") < length($i) && i <= NF; i++)
-              tstr = sprintf("%s%s", tstr, $i);
-	   prefix = "AddToMenu " substr(tstr, 2, length(tstr) - 2)
-        } else
-	   prefix="AddToMenu " $2;
+	   # not going to handle escaped quotes
+	   first=3;
+	   quoted=substr(label, 1, 1)=="\"" &&
+	      substr(label, length(label), 1)!="\"";
+	   for (i=3;i<=NF && quoted;i++) {
+	      label=label " " $i;
+	      quoted=substr(label, length(label), 1)!="\"";
+	      first=i + 1;
+	   }
+	}
+
+	prefix="AddToMenu " label;
 	next;
 }
 
 /^[ \t]*EndPopup[ \t]*/		{
         if (!inpopup)
-	   print "ERROR: EndPopup outside of popup" >"/dev/stderr";
+	   print "ERROR: EndPopup outside of popup\n" NR ": " $0 >"'$TTY'";
         inpopup=FALSE;
 	prefix="";
 	next;
@@ -383,16 +435,26 @@ BEGIN   {
 /^[ \t]*Cursor[ \t]*/		{ 
 	print "#! " $0 " [deleted]";
 	if (warned[$1]==FALSE) {
-	   print "Warning: " $1 " not in Fvwm2, command dropped" >"/dev/stderr";
+	   print "Warning: " $1 " not in Fvwm2, command dropped" >"'$TTY'";
 	   warned[$1] = TRUE;
 	}
 	next;
 }
 
 /^[ \t]*Pager[ \t]*/		{
-        print "#! " $0 " [deleted]";
+	print "#! " $0 " [deleted]";
+	print "#! An FvwmPager config to emulate builtin pager would be as follows:"
+	print "# *FvwmPagerBack SlateGrey";
+	print "# *FvwmPagerFore Black";
+	print "# *FvwmPagerFont none";
+	print "# *FvwmPagerHilight SlateBlue4";
+	print "# *FvwmPagerGeometry <xsize> <ysize>";
+	print "# *FvwmPagerSmallFont -*-times-medium-r-*-*-*-80-*-*-*-*-*-*";
+	print "# *FvwmPagerDeskTopScale 32";
+	print "# #! Now start pager";
+	print "# Module FvwmPager 0 0";
 	if (warned[$1]==FALSE) {
-           print "Warning: " $1 " omitted, internal pager is obsolete (use FvwmPager)" >"/dev/stderr";
+           print "Warning: " $1 " omitted, internal pager is obsolete (use FvwmPager)" >"'$TTY'";
 	   warned[$1] = TRUE;
 	}
 	next;
@@ -401,7 +463,7 @@ BEGIN   {
 /^[ \t]*PagingDefault[ \t]*/	||
 /^[ \t]*TogglePage[ \t]*/	{
         print "#! " $0 " (use EdgeScroll 0 0)"; next;
-	print "Warning: " $1 " not in Fvwm2, use EdgeScroll">"/dev/stderr";
+	print "Warning: " $1 " not in Fvwm2, use EdgeScroll">"'$TTY'";
 }
 
 ########## Old Internal Pager Colors ###########
@@ -409,7 +471,7 @@ BEGIN   {
 /^[ \t]*PagerBackColor[ \t]*/	{
 	printf ("#!%s (new command=Style FvwmPager Color fore_color/back_color)\n", $0);
 	if (warned[$1]==FALSE) {
-           print "Warning: " $1 " omitted, internal pager is obsolete (use FvwmPager)" >"/dev/stderr";
+           print "Warning: " $1 " omitted, internal pager is obsolete (use FvwmPager)" >"'$TTY'";
 	   warned[$1] = TRUE;
 	}
 	next;
@@ -419,8 +481,8 @@ BEGIN   {
 /^[ \t]*StickyForeColor[ \t]*/	{
 	printf ("#!%s (no sticky foreground color in fvwm2)\n", $0);
 	if (warned[$1]==FALSE) {
-	   print "Warning: StickyForeColor not in fvwm2, omitted" > "/dev/stderr"
-           print "         Use the Style command to assign each sticky window the same ForeColor" > "/dev/stderr"
+	   print "Warning: StickyForeColor not in fvwm2, omitted" > "'$TTY'"
+           print "         Use the Style command to assign each sticky window the same ForeColor" > "'$TTY'"
         }
 	next;
 }
@@ -428,8 +490,8 @@ BEGIN   {
 /^[ \t]*StickyBackColor[ \t]*/	{
 	printf ("#!%s (no sticky background color in fvwm2)\n", $0);
 	if (warned[$1]==FALSE) {
-	   print "Warning: StickyBackColor not in fvwm2, omitted" >"/dev/stderr"
-           print "         Use the Style command to assign each sticky window the same BackColor" > "/dev/stderr"
+	   print "Warning: StickyBackColor not in fvwm2, omitted" >"'$TTY'"
+           print "         Use the Style command to assign each sticky window the same BackColor" > "'$TTY'"
         }
 	next;
 }
@@ -475,17 +537,13 @@ BEGIN   {
     if (warned[$1]==FALSE) {
 	printf ("#!Warning: Keyword \"%s\" not handled yet\n", $1);
 	warned[$1]=TRUE;
-	print "Warning: Unknown keyword "$1" passed through">"/dev/stderr";
+	print "Warning: Unknown keyword "$1" passed through">"'$TTY'";
     }
     print $0;
     next;
 }
 
 END {
-    if (!menustyle) {
-	printf ("\n#Set the foreground, background and stipple color and font for menus\n");
-	printf ("MenuStyle   %s %s %s %s %s\n", dflt["menuforecolor"], dflt["menubackcolor"], dflt["menustipplecolor"], dflt["font"], dflt["mwmmenus"]);
-    }
     if (!hilightcolor) {
 	printf ("\n#Set the foreground and background color for selected windows\n");
 	printf ("HilightColor   %s %s\n", dflt["hiforecolor"], dflt["hibackcolor"]);
